apiVersion: v1
kind: PersistentVolume
metadata:
  name: pipeline-shared-storage
  labels:
    type: local
spec:
  volumeMode: Filesystem
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.30.4
    path: "/mnt/kube"


---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pipeline-shared-storage-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi